title: Your awesome title
author: Joon
email: yah-myemail@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a test. And not really worth looking at. 

# social links
twitter_username: noojgnoy
github_username:  joon-aca

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
